services:
  miair-next:
    image: mrdeer1997/miair-next:latest
    container_name: miair-next
    network_mode: host
    restart: unless-stopped
    environment:
      - MIAIR_WEB_PORT=8300
      - MIAIR_GITHUB_REPO=deerwan/miair-next
      - MIAIR_TOKEN_EXPIRE_HOURS=24
    volumes:
      - ./data:/app/data
